### PR TITLE
Dataframe

### PR DESCRIPTION
**Pull request by johnwalicki**
This receive_traces_df.py example uses the MQTT client.loop_start() 
The MQTT on_connect() moves to a separate thread.   It adds the new accelerometer data to a dataframe.
The main thread monitors the dataframe and prints the new data.

### CODE REVIEW

**Review by EdrianI — CHANGES_REQUESTED** [review]
IMO, receive_traces.py should be updated with these changes instead of creating a new file.

Additionally, all pull requests are scanned with a Python linter called Black. Right now this PR is failing the check. Here is more information on Black https://github.com/psf/black

**Comment by johnwalicki** [comment]
@EdrianI Do I need to run the linter on my local system to figure out *why* its failing the linter check?  The report doesn't tell me.

**Comment by johnwalicki** [comment]
> receive_traces.py should be updated with these changes

The subtle difference is that receive_traces.py prints the real time accelerometer data MQTT events to the console only.  Its a good example.

This receive_traces_df.py prints the data in the main thread, runs the MQTT loop in a separate thread and stores the entire accelerometer data history in a dataframe.   Another good example but maybe a slightly different use case?

Both are example building blocks for what might be implemented in the larger detection scripts.  To be honest, they aren't necessarily required - other than learning examples which we needed to walk ourselves through.

If we think I should merge the patch into the original script, I can do that.  I write lots of small iterative use cases.

**Comment by johnwalicki** [comment]
The next program that I would imagine writing is derivatives of this script.

1. One script might restructure the dataframe using pandas json_normalize() 
https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html
so that the dataframe can be organized for more than device (which might be expected if the earthquake triggers several sensors that need to be correlated) 

2. Another script could prune the dataframe for 10 seconds (or whatever the appropriate seismology algorithm requires)

The point being... small incremental steps that work towards the final goal (I'm not a seismologist so not even certain that that looks like)

Like in grade school, we get points for showing our intermediate work in each step.  The answer is important, how got there is important too.  Especially if we go down the wrong path.  Vaclav can grab what he needs.

**Comment by johnwalicki** [comment]
@vkuna - would the above ^^^ be useful as intermediary examples?
Maybe the src/receive* python scripts move to an examples/ directory ?

**Comment by EdrianI** [comment]
> @EdrianI Do I need to run the linter on my local system to figure out _why_ its failing the linter check? The report doesn't tell me.

Take a look at the Black documentation. The linter action ensures that each file in a Pull Request follows Black's formatting rules. The linter can also automatically fix a file's formatting for you (in most cases) by running black against the file with `black <file_name>`. If you want to know specifics about what needs to be changed the linter provides that information on the cli options to use in the documentation I linked above.

**Comment by EdrianI** [comment]
I definitely lean against having example/sample scripts of this nature being in any GitHub repository. If there is going to be a sample script, it should focus on how to utilize an API or Library provided by the repository. For example, if seismology was to become a pip installable library, having a sample that shows how to use seismology would make sense.

**Comment by vkuna** [comment]
Hi. I am working on this right now (sorry some work with the icelandic volcano eruption fell on my table so that slowed me down). I am taking the approach we talked about yesterday, changed the receive_traces.py and receive_devices.py to classes so I can run them at the same time as the rest of the scripts and access the same pandas dataframe which gets updated as more data come.

**Comment by johnwalicki** [comment]
Black had some dumb whitespace complaints

I think we should merge this MQTT + DataFrame example.  Vaclav can choose to use it as a foundation.  If we don't want to keep the receive* scripts around in a examples/ directory, we can delete them in the future.

**Comment by johnwalicki** [comment]
Let's merge this PR and this receive_traces_df.py
None of the receive* scripts are part of the long term solution.  Vaclav will use these examples during the detection.py rewrite.

**Comment by EdrianI** [comment]
If Vaclav is going to work into creating classes out of these scripts then there is no reason to add more versions of the receive_* scripts. If Vaclav wants to use this file as a reference he can do so in this PR or copy the file locally. The remaining recieve_* scripts can be removed when a PR is opened that adds the class version of the scripts.

**Comment by johnwalicki** [comment]
@vkuna If you're interested in running the MQTT loop in a secondary python thread or using a pandas dataframe to store incoming MQTT data, grab the receive_traces_df.py from this branch:
https://github.com/openeew/openeew-seismology/blob/dataframe/src/receive_traces_df.py

**Comment by EdrianI** [comment]
Since this PR should not be merged, we'll close the PR and keep the branch containing the work available for reference.

**Pull request closed without merging**
